include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**, lib/**.g.dart, test/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  errors:
    always_use_package_imports: error
    require_trailing_commas: error
    hash_and_equals: error
    always_put_required_named_parameters_first: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_function_literals_in_foreach_calls: error
    avoid_multiple_declarations_per_line: error
    avoid_positional_boolean_parameters: error
    avoid_returning_null: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_void_async: error
    camel_case_types: error
    directives_ordering: error
    file_names: error
    implementation_imports: error
    missing_whitespace_between_adjacent_strings: warning
    no_runtimeType_toString: warning
    prefer_function_declarations_over_variables: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_single_quotes: warning
    omit_local_variable_types: false

linter:
  rules:
    - always_use_package_imports
    - require_trailing_commas
    - hash_and_equals
    - always_put_required_named_parameters_first
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_void_async
    - camel_case_types
    - directives_ordering
    - file_names
    - implementation_imports
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_mixin
    - prefer_null_aware_operators
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_setters_to_change_properties
    - use_to_and_as_if_applicable



